#!/bin/bash
#cowsay -f ren yut.
#cat /etc/bannerDZ
#ifconfig en1 | awk '/inet / {print $2}'

alias today='grep $(date +%m/%d) /usr/share/calendar/calendar.history'
alias vpr='vim /Users/lalanza808/.bash_profile'
alias la='ls -a'
alias l='ls'
alias ll='ls -l'
alias fix='chmod +x $1'
alias c=clear
alias ns="netstat -na | egrep 'Proto|LISTEN'"
alias pingall="nmap -sP 192.168.1.0/24 -n | awk '/report/' | sed s'/Nmap scan report for //'"

function md() {
	mkdir -p "$@" && cd "$@"
}

function cdl() {
	cd "$@" && ls
}

function del() {
	mv "$@" ~/.Trash/
}

function starcraft() {
	clear
	echo -e "Starting in \n3.....\n2.....\n1....." | pv -qL 10
	open -W /Users/lalanza808/Software/games/Starcraftpack/Starcraft-Broodwar.dmg
	open -W /Applications/Starcraft\ Folder/Starcraft
	eject
	exit
}

export PS1='\[\e[0;36m\]\u | \W »\[\e[0m\] '

